export const PROJECTS_CLIENT = 'PROJECTS_CLIENT';
export const VARIABLES_CLIENT = 'VARIABLES_CLIENT';
export const ARTIFACT_STORAGE_CLIENT = 'ARTIFACT_STORAGE_CLIENT';
export const EVENTS_CLIENT = 'EVENTS_CLIENT';
