export const ERROR_CODES = {
  INTERNAL: 'SNAPPER_INTERNAL_ERROR',
  VALIDATION: 'SNAPPER_VALIDATION_ERROR',
  NOT_FOUND: 'SNAPPER_NOT_FOUND',
  CONFLICT: 'SNAPPER_CONFLICT',
  TIMEOUT: 'SNAPPER_TIMEOUT',
  UNAVAILABLE: 'SNAPPER_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
